name: Checkmarx One Scan
on:
  pull_request:
  push:
    branches:
        - main
        - master
        - dev
        - NewMainNotExp
        - 4.00.2
        
env:
 # platforms: Dockerfile
  scanTypes: iac-security,sast,sca
  threshold: iac-security-high=1=,iac-security-medium=1,iac-securitylow=1    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main
        with:
          project_name: aeco-bim-ige-xao-rnd-poland/igexao_poland_see_log
          cx_tenant: Cx_Seg
          base_uri: https://eu.ast.checkmarx.net
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          additional_params: --debug --project-tags 1CxOne-Users
    #      additional_params: --scan-types ${{ env.scanTypes }} --file-filter "!src/, !.git/, !*.java, !*.iml, !*.json, !*.jar" --debug



    
         
     



